[[100 ошибок в Go и как их избежать]]

При написании http обработчика можно забыть про `return` после ответа на http-запрос
```go
func handler(w http.ResponseWriter, req *http.Request) {
	err := foo(req)
	if err != nil {
		http.Error(w, "foo", http.StatusInternalServerError)
	}
	// ...
}
```
Если `foo` возвращает ошибку, то она будет обработана с помощью http.Error, который отвечает на запрос сообщением об ошибке `foo` и кодом 500. Проблема в том, что если мы войдем в ветку `if err != nil`, выполнение приложение продолжится, так как `http.Error` не останавливает обработчик.
Каковы последствия? С точки зрения HTTP, если мы далее запишем успешный статус код, то это считается преизбыточным, поэтому мы получим предупреждение. С точки зрения выполнения мы продолжим выполнение функции, которая должна была быть остановлена.
Чтобы исправить эту ошибку, надо добавить пустой `return` после `http.Error`
```go
func handler(w http.ResponseWriter, req *http.Request) {
	err := foo(req)
	if err != nil {
		http.Error(w, "foo", http.StatusInternalServerError)
		return
	}
	// ...
}
```